CREATE SCHEMA IF NOT EXISTS raw;

DROP TABLE IF EXISTS raw.orders_raw;

CREATE TABLE IF NOT EXISTS raw.orders_raw (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    business_date DATE NOT NULL,
    ingested_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    source_file VARCHAR(50) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_raw_order_id
    ON raw.orders_raw (order_id);

CREATE INDEX IF NOT EXISTS idx_orders_raw_business_date
    ON raw.orders_raw (business_date);

CREATE INDEX IF NOT EXISTS idx_orders_raw_ingested_at
    ON raw.orders_raw (ingested_at);